In [8]:
import pandas as pd
import numpy as np

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
path=r"/content/drive/MyDrive/Codsoft/datasets/Genre Classification Dataset/train_data.txt"

In [10]:
data = pd.read_csv(path, sep=' ::: ', engine='python', names=['Title', 'Genre', 'Description'], nrows=10000)

In [11]:
data

,Title,Genre,Description
1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his doc...
2,Cupid (1997),thriller,A brother and sister with a past incestuous re...
3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fiel...
4,The Secret Sin (1915),drama,To help their unemployed father make ends meet...
5,The Unrecovered (2007),drama,The film's title refers not only to the un-rec...
...,...,...,...
9996,"""Friday Night Cranks"" (2007/I)",reality-tv,The show began with Jared and Kristen in 2007....
9997,Donkey in the City: 3D Animation Film (????),animation,The center characters of the film are two kids...
9998,Ashland (2007),drama,"Ashland is the story of Ash Slavin, a lonely a..."
9999,Whispering Smith (1926),western,Railroad foreman Murray Sinclair is dismissed ...
10000,GHR: The Great Airspace Chase (2017),adventure,Cruise the radio airwaves to assist the GHR (G...

In [12]:
data.nunique()

Title          10000
Genre             27
Description     9995
dtype: int64

In [13]:
data['Genre'].value_counts()

drama          2466
documentary    2410
comedy         1373
short           947
horror          396
thriller        326
action          245
western         202
reality-tv      165
family          148
adventure       137
music           137
romance         118
sci-fi          118
adult           117
animation        91
sport            84
crime            78
talk-show        77
fantasy          67
mystery          58
musical          54
biography        49
history          45
game-show        38
news             32
war              22
Name: Genre, dtype: int64

In [14]:
data.isna().sum()

Title          0
Genre          0
Description    0
dtype: int64

In [15]:
import category_encoders as ce

In [16]:
encoder=ce.OrdinalEncoder(cols=["Genre"])

In [17]:
data2=encoder.fit_transform(data)

In [18]:
data2

,Title,Genre,Description
1,Oscar et la dame rose (2009),1,Listening in to a conversation between his doc...
2,Cupid (1997),2,A brother and sister with a past incestuous re...
3,"Young, Wild and Wonderful (1980)",3,As the bus empties the students for their fiel...
4,The Secret Sin (1915),1,To help their unemployed father make ends meet...
5,The Unrecovered (2007),1,The film's title refers not only to the un-rec...
...,...,...,...
9996,"""Friday Night Cranks"" (2007/I)",7,The show began with Jared and Kristen in 2007....
9997,Donkey in the City: 3D Animation Film (????),10,The center characters of the film are two kids...
9998,Ashland (2007),1,"Ashland is the story of Ash Slavin, a lonely a..."
9999,Whispering Smith (1926),18,Railroad foreman Murray Sinclair is dismissed ...
10000,GHR: The Great Airspace Chase (2017),16,Cruise the radio airwaves to assist the GHR (G...

In [19]:
data3=data2

In [20]:
data3['Title'] = data3['Title'].str.lower()
data3['Description'] = data3['Description'].str.lower()
data3.head()

,Title,Genre,Description
1,oscar et la dame rose (2009),1,listening in to a conversation between his doc...
2,cupid (1997),2,a brother and sister with a past incestuous re...
3,"young, wild and wonderful (1980)",3,as the bus empties the students for their fiel...
4,the secret sin (1915),1,to help their unemployed father make ends meet...
5,the unrecovered (2007),1,the film's title refers not only to the un-rec...

In [21]:
import nltk

In [22]:
from nltk.tokenize import word_tokenize

In [24]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [25]:
data3['Title_Tokens'] = data3['Title'].apply(lambda text: word_tokenize(text))
data3['Description_Tokens'] = data3['Description'].apply(lambda text: word_tokenize(text))

In [26]:
print(data3[['Title', 'Title_Tokens', 'Description', 'Description_Tokens']])

                                              Title  \
1                      oscar et la dame rose (2009)
2                                      cupid (1997)
3                  young, wild and wonderful (1980)
4                             the secret sin (1915)
5                            the unrecovered (2007)
...                                             ...
9996                 "friday night cranks" (2007/i)
9997   donkey in the city: 3d animation film (????)
9998                                 ashland (2007)
9999                        whispering smith (1926)
10000          ghr: the great airspace chase (2017)

                                            Title_Tokens  \
1                [oscar, et, la, dame, rose, (, 2009, )]
2                                    [cupid, (, 1997, )]
3           [young, ,, wild, and, wonderful, (, 1980, )]
4                         [the, secret, sin, (, 1915, )]
5                         [the, unrecovered, (, 2007, )]
...                                                  ...
9996       [``, friday, night, cranks, '', (, 2007/i, )]
9997   [donkey, in, the, city, :, 3d, animation, film...
9998                               [ashland, (, 2007, )]
9999                     [whispering, smith, (, 1926, )]
10000  [ghr, :, the, great, airspace, chase, (, 2017, )]

                                             Description  \
1      listening in to a conversation between his doc...
2      a brother and sister with a past incestuous re...
3      as the bus empties the students for their fiel...
4      to help their unemployed father make ends meet...
5      the film's title refers not only to the un-rec...
...                                                  ...
9996   the show began with jared and kristen in 2007....
9997   the center characters of the film are two kids...
9998   ashland is the story of ash slavin, a lonely a...
9999   railroad foreman murray sinclair is dismissed ...
10000  cruise the radio airwaves to assist the ghr (g...

                                      Description_Tokens
1      [listening, in, to, a, conversation, between, ...
2      [a, brother, and, sister, with, a, past, inces...
3      [as, the, bus, empties, the, students, for, th...
4      [to, help, their, unemployed, father, make, en...
5      [the, film, 's, title, refers, not, only, to, ...
...                                                  ...
9996   [the, show, began, with, jared, and, kristen, ...
9997   [the, center, characters, of, the, film, are, ...
9998   [ashland, is, the, story, of, ash, slavin, ,, ...
9999   [railroad, foreman, murray, sinclair, is, dism...
10000  [cruise, the, radio, airwaves, to, assist, the...

[10000 rows x 4 columns]

In [27]:
data3

,Title,Genre,Description,Title_Tokens,Description_Tokens
1,oscar et la dame rose (2009),1,listening in to a conversation between his doc...,"[oscar, et, la, dame, rose, (, 2009, )]","[listening, in, to, a, conversation, between, ..."
2,cupid (1997),2,a brother and sister with a past incestuous re...,"[cupid, (, 1997, )]","[a, brother, and, sister, with, a, past, inces..."
3,"young, wild and wonderful (1980)",3,as the bus empties the students for their fiel...,"[young, ,, wild, and, wonderful, (, 1980, )]","[as, the, bus, empties, the, students, for, th..."
4,the secret sin (1915),1,to help their unemployed father make ends meet...,"[the, secret, sin, (, 1915, )]","[to, help, their, unemployed, father, make, en..."
5,the unrecovered (2007),1,the film's title refers not only to the un-rec...,"[the, unrecovered, (, 2007, )]","[the, film, 's, title, refers, not, only, to, ..."
...,...,...,...,...,...
9996,"""friday night cranks"" (2007/i)",7,the show began with jared and kristen in 2007....,"[``, friday, night, cranks, '', (, 2007/i, )]","[the, show, began, with, jared, and, kristen, ..."
9997,donkey in the city: 3d animation film (????),10,the center characters of the film are two kids...,"[donkey, in, the, city, :, 3d, animation, film...","[the, center, characters, of, the, film, are, ..."
9998,ashland (2007),1,"ashland is the story of ash slavin, a lonely a...","[ashland, (, 2007, )]","[ashland, is, the, story, of, ash, slavin, ,, ..."
9999,whispering smith (1926),18,railroad foreman murray sinclair is dismissed ...,"[whispering, smith, (, 1926, )]","[railroad, foreman, murray, sinclair, is, dism..."
10000,ghr: the great airspace chase (2017),16,cruise the radio airwaves to assist the ghr (g...,"[ghr, :, the, great, airspace, chase, (, 2017, )]","[cruise, the, radio, airwaves, to, assist, the..."

In [28]:
data4=data3.drop(["Title","Description"],axis=1)

In [29]:
data4

,Genre,Title_Tokens,Description_Tokens
1,1,"[oscar, et, la, dame, rose, (, 2009, )]","[listening, in, to, a, conversation, between, ..."
2,2,"[cupid, (, 1997, )]","[a, brother, and, sister, with, a, past, inces..."
3,3,"[young, ,, wild, and, wonderful, (, 1980, )]","[as, the, bus, empties, the, students, for, th..."
4,1,"[the, secret, sin, (, 1915, )]","[to, help, their, unemployed, father, make, en..."
5,1,"[the, unrecovered, (, 2007, )]","[the, film, 's, title, refers, not, only, to, ..."
...,...,...,...
9996,7,"[``, friday, night, cranks, '', (, 2007/i, )]","[the, show, began, with, jared, and, kristen, ..."
9997,10,"[donkey, in, the, city, :, 3d, animation, film...","[the, center, characters, of, the, film, are, ..."
9998,1,"[ashland, (, 2007, )]","[ashland, is, the, story, of, ash, slavin, ,, ..."
9999,18,"[whispering, smith, (, 1926, )]","[railroad, foreman, murray, sinclair, is, dism..."
10000,16,"[ghr, :, the, great, airspace, chase, (, 2017, )]","[cruise, the, radio, airwaves, to, assist, the..."

In [30]:
data5=data4

In [31]:
def remove_numbers(tokens):
    return [ token for token in tokens if not token.isdigit()]


data5['Title_Tokens'] = data5['Title_Tokens'].apply(remove_numbers)
data5['Description_Tokens'] = data5['Description_Tokens'].apply(remove_numbers)

In [32]:
import string

def remove_punctuations(tokens):
    return [ token for token in tokens if not token in string.punctuation ]

data5['Title_Tokens'] = data5['Title_Tokens'].apply(remove_punctuations)
data5['Description_Tokens'] = data5['Description_Tokens'].apply(remove_punctuations)

In [33]:
data5

,Genre,Title_Tokens,Description_Tokens
1,1,"[oscar, et, la, dame, rose]","[listening, in, to, a, conversation, between, ..."
2,2,[cupid],"[a, brother, and, sister, with, a, past, inces..."
3,3,"[young, wild, and, wonderful]","[as, the, bus, empties, the, students, for, th..."
4,1,"[the, secret, sin]","[to, help, their, unemployed, father, make, en..."
5,1,"[the, unrecovered]","[the, film, 's, title, refers, not, only, to, ..."
...,...,...,...
9996,7,"[``, friday, night, cranks, '', 2007/i]","[the, show, began, with, jared, and, kristen, ..."
9997,10,"[donkey, in, the, city, 3d, animation, film]","[the, center, characters, of, the, film, are, ..."
9998,1,[ashland],"[ashland, is, the, story, of, ash, slavin, a, ..."
9999,18,"[whispering, smith]","[railroad, foreman, murray, sinclair, is, dism..."
10000,16,"[ghr, the, great, airspace, chase]","[cruise, the, radio, airwaves, to, assist, the..."

In [34]:
from nltk.corpus import stopwords

In [37]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [38]:
stop_words = set(stopwords.words('english'))

In [39]:
def remove_stopwords(tokens):
    filtered_tokens = [token for token in tokens if token.lower() not in stop_words]
    return filtered_tokens

In [40]:
data5['Title_Tokens'] = data5['Title_Tokens'].apply(remove_stopwords)
data5['Description_Tokens'] = data5['Description_Tokens'].apply(remove_stopwords)

In [41]:
data5

,Genre,Title_Tokens,Description_Tokens
1,1,"[oscar, et, la, dame, rose]","[listening, conversation, doctor, parents, 10-..."
2,2,[cupid],"[brother, sister, past, incestuous, relationsh..."
3,3,"[young, wild, wonderful]","[bus, empties, students, field, trip, museum, ..."
4,1,"[secret, sin]","[help, unemployed, father, make, ends, meet, e..."
5,1,[unrecovered],"[film, 's, title, refers, un-recovered, bodies..."
...,...,...,...
9996,7,"[``, friday, night, cranks, '', 2007/i]","[show, began, jared, kristen, 2007., kristen, ..."
9997,10,"[donkey, city, 3d, animation, film]","[center, characters, film, two, kids-a, boy, g..."
9998,1,[ashland],"[ashland, story, ash, slavin, lonely, depresse..."
9999,18,"[whispering, smith]","[railroad, foreman, murray, sinclair, dismisse..."
10000,16,"[ghr, great, airspace, chase]","[cruise, radio, airwaves, assist, ghr, grindho..."

In [42]:
data6=data5

In [43]:
from nltk.stem import WordNetLemmatizer

In [44]:
lemmatizer = WordNetLemmatizer()

In [45]:
def lemmatize_tokens(tokens):
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return lemmatized_tokens

In [47]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [48]:
data6['Title_Tokens_Lemmatized'] = data6['Title_Tokens'].apply(lemmatize_tokens)
data6['Description_Tokens_Lemmatized'] = data6['Description_Tokens'].apply(lemmatize_tokens)

In [49]:
data6

,Genre,Title_Tokens,Description_Tokens,Title_Tokens_Lemmatized,Description_Tokens_Lemmatized
1,1,"[oscar, et, la, dame, rose]","[listening, conversation, doctor, parents, 10-...","[oscar, et, la, dame, rose]","[listening, conversation, doctor, parent, 10-y..."
2,2,[cupid],"[brother, sister, past, incestuous, relationsh...",[cupid],"[brother, sister, past, incestuous, relationsh..."
3,3,"[young, wild, wonderful]","[bus, empties, students, field, trip, museum, ...","[young, wild, wonderful]","[bus, empty, student, field, trip, museum, nat..."
4,1,"[secret, sin]","[help, unemployed, father, make, ends, meet, e...","[secret, sin]","[help, unemployed, father, make, end, meet, ed..."
5,1,[unrecovered],"[film, 's, title, refers, un-recovered, bodies...",[unrecovered],"[film, 's, title, refers, un-recovered, body, ..."
...,...,...,...,...,...
9996,7,"[``, friday, night, cranks, '', 2007/i]","[show, began, jared, kristen, 2007., kristen, ...","[``, friday, night, crank, '', 2007/i]","[show, began, jared, kristen, 2007., kristen, ..."
9997,10,"[donkey, city, 3d, animation, film]","[center, characters, film, two, kids-a, boy, g...","[donkey, city, 3d, animation, film]","[center, character, film, two, kids-a, boy, gi..."
9998,1,[ashland],"[ashland, story, ash, slavin, lonely, depresse...",[ashland],"[ashland, story, ash, slavin, lonely, depresse..."
9999,18,"[whispering, smith]","[railroad, foreman, murray, sinclair, dismisse...","[whispering, smith]","[railroad, foreman, murray, sinclair, dismisse..."
10000,16,"[ghr, great, airspace, chase]","[cruise, radio, airwaves, assist, ghr, grindho...","[ghr, great, airspace, chase]","[cruise, radio, airwave, assist, ghr, grindhou..."

In [50]:
data7=data6.drop(["Title_Tokens","Description_Tokens"],axis=1)

In [51]:
data7

,Genre,Title_Tokens_Lemmatized,Description_Tokens_Lemmatized
1,1,"[oscar, et, la, dame, rose]","[listening, conversation, doctor, parent, 10-y..."
2,2,[cupid],"[brother, sister, past, incestuous, relationsh..."
3,3,"[young, wild, wonderful]","[bus, empty, student, field, trip, museum, nat..."
4,1,"[secret, sin]","[help, unemployed, father, make, end, meet, ed..."
5,1,[unrecovered],"[film, 's, title, refers, un-recovered, body, ..."
...,...,...,...
9996,7,"[``, friday, night, crank, '', 2007/i]","[show, began, jared, kristen, 2007., kristen, ..."
9997,10,"[donkey, city, 3d, animation, film]","[center, character, film, two, kids-a, boy, gi..."
9998,1,[ashland],"[ashland, story, ash, slavin, lonely, depresse..."
9999,18,"[whispering, smith]","[railroad, foreman, murray, sinclair, dismisse..."
10000,16,"[ghr, great, airspace, chase]","[cruise, radio, airwave, assist, ghr, grindhou..."

In [52]:
from transformers import AutoTokenizer, AutoModel
import torch

In [53]:
model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

In [86]:
def get_bert_embeddings(tokens):
    # Tokenize the text
    tokenized_text = tokenizer.tokenize(' '.join(tokens))

    # Truncate or split text if it exceeds BERT model's max token limit
    max_token_limit = tokenizer.max_model_input_sizes[model_name]
    if len(tokenized_text) > max_token_limit:
        tokenized_text = tokenized_text[:max_token_limit]

    if not tokenized_text:
        # Handle the case where tokenized_text is empty
        return None

    # Convert tokens to input IDs
    input_ids = tokenizer.convert_tokens_to_ids(tokenized_text)

    # Create a tensor from the input IDs
    inputs = torch.tensor(input_ids).unsqueeze(0)  # Add batch dimension

    # Get the BERT embeddings for the text
    with torch.no_grad():
        outputs = model(inputs)

    # Extract the embeddings from the BERT model
    embeddings = outputs[0].mean(dim=1)  # Use mean pooling

    return embeddings

In [87]:
data8=data7

In [88]:
data8

,Genre,Title_Tokens_Lemmatized,Description_Tokens_Lemmatized
1,1,"[oscar, et, la, dame, rose]","[listening, conversation, doctor, parent, 10-y..."
2,2,[cupid],"[brother, sister, past, incestuous, relationsh..."
3,3,"[young, wild, wonderful]","[bus, empty, student, field, trip, museum, nat..."
4,1,"[secret, sin]","[help, unemployed, father, make, end, meet, ed..."
5,1,[unrecovered],"[film, 's, title, refers, un-recovered, body, ..."
...,...,...,...
9996,7,"[``, friday, night, crank, '', 2007/i]","[show, began, jared, kristen, 2007., kristen, ..."
9997,10,"[donkey, city, 3d, animation, film]","[center, character, film, two, kids-a, boy, gi..."
9998,1,[ashland],"[ashland, story, ash, slavin, lonely, depresse..."
9999,18,"[whispering, smith]","[railroad, foreman, murray, sinclair, dismisse..."
10000,16,"[ghr, great, airspace, chase]","[cruise, radio, airwave, assist, ghr, grindhou..."

In [89]:
data8['Title_BERT_Embeddings'] = data7['Title_Tokens_Lemmatized'].apply(get_bert_embeddings)
data8['Description_BERT_Embeddings'] = data7['Description_Tokens_Lemmatized'].apply(get_bert_embeddings)

Token indices sequence length is longer than the specified maximum sequence length for this model (1289 > 512). Running this sequence through the model will result in indexing errors

In [90]:
print(data8[['Title_BERT_Embeddings', 'Description_BERT_Embeddings']])

                                   Title_BERT_Embeddings  \
1      [[tensor(0.0447), tensor(0.6504), tensor(0.680...
2      [[tensor(-0.3483), tensor(-0.0908), tensor(-0....
3      [[tensor(0.2902), tensor(0.1930), tensor(0.075...
4      [[tensor(0.2119), tensor(0.3712), tensor(0.444...
5      [[tensor(-0.0717), tensor(-0.5298), tensor(0.1...
...                                                  ...
9996   [[tensor(0.3276), tensor(0.2904), tensor(0.438...
9997   [[tensor(0.1116), tensor(0.2132), tensor(0.136...
9998   [[tensor(-0.1808), tensor(0.1075), tensor(-0.1...
9999   [[tensor(0.1922), tensor(0.5235), tensor(0.047...
10000  [[tensor(-0.2583), tensor(0.5400), tensor(0.68...

                             Description_BERT_Embeddings
1      [[tensor(-0.2926), tensor(0.1787), tensor(0.65...
2      [[tensor(0.3120), tensor(0.2371), tensor(0.639...
3      [[tensor(0.2774), tensor(-0.0382), tensor(0.63...
4      [[tensor(0.0178), tensor(0.1379), tensor(0.480...
5      [[tensor(0.2955), tensor(0.1888), tensor(0.613...
...                                                  ...
9996   [[tensor(0.0982), tensor(-0.6854), tensor(0.45...
9997   [[tensor(-0.1497), tensor(-0.0056), tensor(0.5...
9998   [[tensor(0.0012), tensor(0.0315), tensor(0.577...
9999   [[tensor(-0.2558), tensor(0.0915), tensor(0.71...
10000  [[tensor(-0.0600), tensor(0.0705), tensor(0.61...

[10000 rows x 2 columns]

In [91]:
data8.dtypes

Genre                             int64
Title_Tokens_Lemmatized          object
Description_Tokens_Lemmatized    object
Title_BERT_Embeddings            object
Description_BERT_Embeddings      object
dtype: object

In [93]:
data9=data8.drop(["Title_Tokens_Lemmatized","Description_Tokens_Lemmatized"],axis=1)

In [94]:
data9

,Genre,Title_BERT_Embeddings,Description_BERT_Embeddings
1,1,"[[tensor(0.0447), tensor(0.6504), tensor(0.680...","[[tensor(-0.2926), tensor(0.1787), tensor(0.65..."
2,2,"[[tensor(-0.3483), tensor(-0.0908), tensor(-0....","[[tensor(0.3120), tensor(0.2371), tensor(0.639..."
3,3,"[[tensor(0.2902), tensor(0.1930), tensor(0.075...","[[tensor(0.2774), tensor(-0.0382), tensor(0.63..."
4,1,"[[tensor(0.2119), tensor(0.3712), tensor(0.444...","[[tensor(0.0178), tensor(0.1379), tensor(0.480..."
5,1,"[[tensor(-0.0717), tensor(-0.5298), tensor(0.1...","[[tensor(0.2955), tensor(0.1888), tensor(0.613..."
...,...,...,...
9996,7,"[[tensor(0.3276), tensor(0.2904), tensor(0.438...","[[tensor(0.0982), tensor(-0.6854), tensor(0.45..."
9997,10,"[[tensor(0.1116), tensor(0.2132), tensor(0.136...","[[tensor(-0.1497), tensor(-0.0056), tensor(0.5..."
9998,1,"[[tensor(-0.1808), tensor(0.1075), tensor(-0.1...","[[tensor(0.0012), tensor(0.0315), tensor(0.577..."
9999,18,"[[tensor(0.1922), tensor(0.5235), tensor(0.047...","[[tensor(-0.2558), tensor(0.0915), tensor(0.71..."
10000,16,"[[tensor(-0.2583), tensor(0.5400), tensor(0.68...","[[tensor(-0.0600), tensor(0.0705), tensor(0.61..."

In [95]:
data9.dtypes

Genre                           int64
Title_BERT_Embeddings          object
Description_BERT_Embeddings    object
dtype: object

In [97]:
import numpy as np

def extract_first_element(x):
    if x is not None and len(x) > 0:
        return np.array(x[0])
    else:
        return np.array([])  # Handle None or empty lists

In [98]:
data9['Title_BERT_Embeddings'] = data9['Title_BERT_Embeddings'].apply(extract_first_element)
data9['Description_BERT_Embeddings'] = data9['Description_BERT_Embeddings'].apply(extract_first_element)

In [99]:
data9

,Genre,Title_BERT_Embeddings,Description_BERT_Embeddings
1,1,"[0.044672884, 0.6504486, 0.68019426, 0.2425015...","[-0.29262975, 0.17872958, 0.6508268, -0.144646..."
2,2,"[-0.34832758, -0.09079007, -0.073836915, 0.003...","[0.31198016, 0.23713805, 0.63927954, -0.034037..."
3,3,"[0.290186, 0.19301097, 0.07582923, -0.4347234,...","[0.27744582, -0.03822311, 0.63090056, 0.166171..."
4,1,"[0.21185112, 0.3712456, 0.444283, -0.31585044,...","[0.017798033, 0.13790017, 0.48079947, -0.03666..."
5,1,"[-0.07167867, -0.52977353, 0.17739886, -0.3320...","[0.29547742, 0.18877852, 0.6138233, -0.0385563..."
...,...,...,...
9996,7,"[0.32755992, 0.29044437, 0.43819737, -0.040571...","[0.098249845, -0.68544304, 0.4538793, -0.03721..."
9997,10,"[0.111601375, 0.21320987, 0.13668033, -0.08490...","[-0.14970194, -0.005627429, 0.56326485, -0.049..."
9998,1,"[-0.18082415, 0.10752606, -0.12383568, 0.43122...","[0.001227965, 0.031452965, 0.5774707, -0.14599..."
9999,18,"[0.19217497, 0.5235442, 0.04729774, -0.0234664...","[-0.25575116, 0.09152964, 0.7197962, 0.0590428..."
10000,16,"[-0.25833204, 0.5399519, 0.68051, 0.18802664, ...","[-0.06003426, 0.07045823, 0.61164796, -0.15332..."

In [100]:
data9.dtypes

Genre                           int64
Title_BERT_Embeddings          object
Description_BERT_Embeddings    object
dtype: object

In [101]:
for item in data9['Description_BERT_Embeddings']:
    if isinstance(item, str):
        print(type(item))
    else:
        print(f"Non-string type: {type(item)}")

Streaming output truncated to the last 5000 lines.
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>
Non-string type: <class 'numpy.ndarray'>

In [102]:
def array_to_string(arr):
    if isinstance(arr, np.ndarray):
        return np.array2string(arr, separator=',', precision=2)  # You can adjust separator and precision as needed
    else:
        return str(arr)

In [103]:
data9['Title_BERT_Embeddings'] = data9['Title_BERT_Embeddings'].apply(array_to_string)

In [104]:
data9['Title_BERT_Embeddings'] = data9['Title_BERT_Embeddings'].astype(str)

In [105]:
data9['Title_BERT_Embeddings'] = data9['Title_BERT_Embeddings'].str.strip()

In [106]:
data9.dtypes

Genre                           int64
Title_BERT_Embeddings          object
Description_BERT_Embeddings    object
dtype: object

In [107]:
data9

,Genre,Title_BERT_Embeddings,Description_BERT_Embeddings
1,1,"[ 4.47e-02, 6.50e-01, 6.80e-01, 2.43e-01, 3.01...","[-0.29262975, 0.17872958, 0.6508268, -0.144646..."
2,2,"[-3.48e-01,-9.08e-02,-7.38e-02, 3.88e-03, 4.33...","[0.31198016, 0.23713805, 0.63927954, -0.034037..."
3,3,"[ 2.90e-01, 1.93e-01, 7.58e-02,-4.35e-01,-2.70...","[0.27744582, -0.03822311, 0.63090056, 0.166171..."
4,1,"[ 2.12e-01, 3.71e-01, 4.44e-01,-3.16e-01, 6.25...","[0.017798033, 0.13790017, 0.48079947, -0.03666..."
5,1,"[-7.17e-02,-5.30e-01, 1.77e-01,-3.32e-01, 3.37...","[0.29547742, 0.18877852, 0.6138233, -0.0385563..."
...,...,...,...
9996,7,"[ 3.28e-01, 2.90e-01, 4.38e-01,-4.06e-02, 1.62...","[0.098249845, -0.68544304, 0.4538793, -0.03721..."
9997,10,"[ 1.12e-01, 2.13e-01, 1.37e-01,-8.49e-02, 2.36...","[-0.14970194, -0.005627429, 0.56326485, -0.049..."
9998,1,"[-1.81e-01, 1.08e-01,-1.24e-01, 4.31e-01,-8.21...","[0.001227965, 0.031452965, 0.5774707, -0.14599..."
9999,18,"[ 1.92e-01, 5.24e-01, 4.73e-02,-2.35e-02,-3.40...","[-0.25575116, 0.09152964, 0.7197962, 0.0590428..."
10000,16,"[-2.58e-01, 5.40e-01, 6.81e-01, 1.88e-01, 2.49...","[-0.06003426, 0.07045823, 0.61164796, -0.15332..."

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(data9, *['Genre'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(data9, *['Title_BERT_Embeddings'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(data9, *['Description_BERT_Embeddings'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plot(df, x_colname, y_colname, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(6 * figscale, 6 * figscale))
  df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha)
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plot(data9, *['Genre', 'Title_BERT_Embeddings'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plot(df, x_colname, y_colname, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(6 * figscale, 6 * figscale))
  df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha)
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plot(data9, *['Title_BERT_Embeddings', 'Description_BERT_Embeddings'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(data9, *['Genre'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(data9, *['Title_BERT_Embeddings'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(data9, *['Description_BERT_Embeddings'], **{})
chart

In [108]:
import re

In [110]:
def extract_numeric(cell):
    try:
        # Use regular expressions to extract numeric values
        numeric_values = re.findall(r'[-+]?\d*\.\d+|\d+', cell)
        # Convert the first extracted value to a float
        if numeric_values:
             return float(numeric_values[0])
        else:
            return None  # Handle the case where no numeric values are found
    except (ValueError, IndexError):
        return None

In [111]:
data9['Title_BERT_Embeddings'] = data9['Title_BERT_Embeddings'].apply(extract_numeric)

In [112]:
data9['Description_BERT_Embeddings'] = data9['Description_BERT_Embeddings'].apply(array_to_string)

In [113]:
data9['Description_BERT_Embeddings'] = data9['Description_BERT_Embeddings'].str.strip()

In [114]:
data9['Description_BERT_Embeddings'] = data9['Description_BERT_Embeddings'].apply(extract_numeric)

In [115]:
data9.dtypes

Genre                            int64
Title_BERT_Embeddings          float64
Description_BERT_Embeddings    float64
dtype: object

In [116]:
data9

       Genre  Title_BERT_Embeddings  Description_BERT_Embeddings
1          1                   4.47                        -2.93
2          2                  -3.48                         3.12
3          3                   2.90                         2.77
4          1                   2.12                         1.78
5          1                  -7.17                         2.95
...      ...                    ...                          ...
9996       7                   3.28                         9.82
9997      10                   1.12                        -1.50
9998       1                  -1.81                         1.23
9999      18                   1.92                        -2.56
10000     16                  -2.58                        -6.00

[10000 rows x 3 columns]

In [117]:
data9.nunique()

Genre                            27
Title_BERT_Embeddings          1740
Description_BERT_Embeddings    1690
dtype: int64

In [118]:
data9.isna().sum()

Genre                           0
Title_BERT_Embeddings          33
Description_BERT_Embeddings     0
dtype: int64

In [136]:
data10=data9.fillna(0)

In [137]:
features=data10.drop(["Genre"],axis=1)

In [138]:
labels=data10["Genre"]

In [139]:
from sklearn.model_selection import train_test_split

In [140]:
x_train,x_test,y_train,y_test=train_test_split(features,labels,test_size=0.2,random_state=13)

In [141]:
from lazypredict.Supervised import LazyClassifier

In [142]:
clf=LazyClassifier(verbose=0,ignore_warnings=True,custom_metric=None)

In [143]:
models,predictions=clf.fit(x_train,x_test,y_train,y_test)

 90%|████████▉ | 26/29 [00:37<00:06,  2.05s/it]

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000221 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 2
[LightGBM] [Info] Start training from score -1.411612
[LightGBM] [Info] Start training from score -3.438121
[LightGBM] [Info] Start training from score -4.544546
[LightGBM] [Info] Start training from score -1.405477
[LightGBM] [Info] Start training from score -1.966113
[LightGBM] [Info] Start training from score -4.753090
[LightGBM] [Info] Start training from score -4.096848
[LightGBM] [Info] Start training from score -3.250625
[LightGBM] [Info] Start training from score -4.710531
[LightGBM] [Info] Start training from score -4.683132
[LightGBM] [Info] Start training from score -3.698930
[LightGBM] [Info] Start training from score -5.035953
[LightGBM] [Info] Start training from score -2.364460
[LightGBM] [Info] Start training from score -4.433320
[LightGBM] [Info] Start training from score -4.314368
[LightGBM] [Info] Start training from score -4.422849
[LightGBM] [Info] Start training from score -4.876323
[LightGBM] [Info] Start training from score -3.937341
[LightGBM] [Info] Start training from score -4.166915
[LightGBM] [Info] Start training from score -5.180534
[LightGBM] [Info] Start training from score -5.349611
[LightGBM] [Info] Start training from score -5.729100
[LightGBM] [Info] Start training from score -5.298317
[LightGBM] [Info] Start training from score -4.465408
[LightGBM] [Info] Start training from score -5.729100
[LightGBM] [Info] Start training from score -5.203007
[LightGBM] [Info] Start training from score -6.214608

100%|██████████| 29/29 [00:43<00:00,  1.48s/it]

In [144]:
models

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
NearestCentroid,0.03,0.06,None,0.01,0.05
AdaBoostClassifier,0.23,0.05,None,0.17,1.06
SGDClassifier,0.26,0.05,None,0.19,0.36
LabelSpreading,0.28,0.05,None,0.20,5.23
LabelPropagation,0.28,0.05,None,0.20,2.51
QuadraticDiscriminantAnalysis,0.28,0.04,None,0.20,0.04
LinearSVC,0.29,0.04,None,0.19,2.15
RidgeClassifierCV,0.29,0.04,None,0.19,0.12
RidgeClassifier,0.29,0.04,None,0.19,0.06
BernoulliNB,0.29,0.04,None,0.19,0.04
CalibratedClassifierCV,0.29,0.04,None,0.19,11.53
GaussianNB,0.28,0.04,None,0.19,0.02
LinearDiscriminantAnalysis,0.28,0.04,None,0.19,0.04
LogisticRegression,0.28,0.04,None,0.19,0.85
SVC,0.28,0.04,None,0.18,7.22
RandomForestClassifier,0.20,0.04,None,0.18,3.15
ExtraTreesClassifier,0.18,0.04,None,0.17,1.81
BaggingClassifier,0.18,0.04,None,0.16,0.48
DecisionTreeClassifier,0.14,0.04,None,0.14,0.09
KNeighborsClassifier,0.23,0.04,None,0.18,0.12
LGBMClassifier,0.23,0.04,None,0.18,5.57
ExtraTreeClassifier,0.15,0.04,None,0.15,0.04
Perceptron,0.15,0.04,None,0.09,0.16
DummyClassifier,0.22,0.04,None,0.08,0.03
PassiveAggressiveClassifier,0.06,0.03,None,0.02,0.16

In [145]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

In [148]:
clf2 = LinearSVC()
clf2.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

LinearSVC()

In [150]:
y_pred = clf2.predict(x_test)

In [151]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.288